services:
  worldmap:
    container_name: worldmap
    image: worldmap
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/opt/project/data
      - ./symbols:/opt/project/symbols
      - ./scripts:/opt/project/scripts
      - ./config:/opt/project/config
    environment:
      - TZ=Pacific/Auckland
    healthcheck:
      # Specifically check for an updated file in the data directory
      test: ["CMD", "find", "/opt/project/data/quake_markers.txt", "-mmin", "-30"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m
