# Makefile for WorldMap Project Suite
# The source is bind-mounted into the dev containers (see docker-compose.override.yml),
# so a CODE edit is already on disk inside the container. You only need to RESTART
# the service's process for Python to re-import it — NOT rebuild the image. `make build`
# is now only for dependency or Dockerfile changes.
# =============================================================================
.PHONY: run stop build rebuild start-desktop-fg stop-desktop psql logs clean purge backup restore refresh-map test bash status help

# Variables
DB_USER = wmap
DB_NAME = worldmap
DB_SERVICE = worldmap_db
BUILDER_SERVICE = layer_builder
DUMP_FILE = worldmap_dump.sql

# Backend services that run your mounted Python code (everything except UI/DB).
BACKEND_SERVICES = shipping_collector data_collector lightning_collector \
                   layer_builder housekeeper map_api

## reload: Apply CODE changes live — just restart (no rebuild)
reload:
ifndef service
	docker compose restart $(BACKEND_SERVICES)
else
	docker compose restart $(service)
endif

## stop: Bring all containers down
stop:
	docker compose down

## start|run|up: Start dev stack (auto-merges docker-compose.override.yml)
up run start:
	docker compose up -d

## build: Rebuild images — only needed for DEPENDENCY changes
build: stop
	docker compose build

## rebuild: Rebuild all images from scratch (no cache)
rebuild:
	docker compose build --no-cache

## prod: Run EXACTLY as a package consumer would
prod:
	docker compose -f docker-compose.yml pull
	docker compose -f docker-compose.yml up -d

## prod-down: Stop the consumer-style stack
prod-down:
	docker compose -f docker-compose.yml down

## logs: Tail all logs; service=name for specific service
logs:
ifndef service
	docker compose logs -f
else
	docker compose logs -f ${service}
endif

## test: Run all tests (optional: make test include=pattern)
test:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Running complete discovery test suite via pytest..."
	docker compose exec $(BUILDER_SERVICE) uv run pytest tests/ -v $(if $(include),-k $(include))
	@read -p "Remove files generated by testing? [y/N] " ans; \
	if [ "$${ans:-N}" = "y" ] || [ "$${ans:-N}" = "Y" ]; then \
	   docker compose exec $(BUILDER_SERVICE) find ./data -type f -name "test_*" -exec rm {} \; ; \
	fi

## bash: Start a bash session in the main BUILDER_SERVICE app
bash:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	docker compose exec $(BUILDER_SERVICE) bash

## lint: Run the linter across the code
lint:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Checking for any issues - without fixing"
	docker compose exec $(BUILDER_SERVICE) uv run ruff check src

## lint-format: Run the linter across the code and format to standard
lint-format:
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Formatting code to consistent standard"
	docker compose exec $(BUILDER_SERVICE) uv run ruff format src

## lint-fix: Run the linter across the code and fix issues
lint-fix: lint-format
	@echo "Ensuring $(BUILDER_SERVICE) container environment is active..."
	docker compose up $(BUILDER_SERVICE) -d
	@echo "Fixing issues.."
	docker compose exec $(BUILDER_SERVICE) uv run ruff check --fix src

## backup: Backup database to local worldmap-dump.sql file
backup:
	@echo "Ensuring worldmap database is running"
	docker compose up $(DB_SERVICE) -d
	@echo "Creating compressed database backup to $(DUMP_FILE)..."
	docker compose exec $(DB_SERVICE) pg_dump -U $(DB_USER) -Fc $(DB_NAME) > $(DUMP_FILE)
	@echo "Backup complete."

## restore: Restores the local worldmap-dump.sql backup
restore:
	@echo "WARNING: This will DELETE and RECREATE the $(DB_NAME) database from $(DUMP_FILE)."
	@if [ ! -f $(DUMP_FILE) ]; then echo "Error: $(DUMP_FILE) not found."; exit 1; fi
	@read -p "Are you sure? [y/N] " ans; \
	if [ "$${ans:-N}" = "y" ] || [ "$${ans:-N}" = "Y" ]; then \
		echo "Stopping backend services" ; \
		docker compose stop $(BACKEND_SERVICES); \
		echo "Ensuring worldmap database is running..." ; \
		docker compose up $(DB_SERVICE) -d && sleep 5 ; \
		echo "Restoring database..." ; \
		cat $(DUMP_FILE) | docker compose exec -T $(DB_SERVICE) pg_restore -U $(DB_USER) -d postgres --clean --create --if-exists ; \
		echo "Restore complete." ; \
		echo "Stopping worldmap database. Backend left as stopped." ; \
		docker compose stop $(DB_SERVICE) ; \
	fi

## clean: Stop containers, remove images
clean:
	docker compose down --rmi all
	@echo "Containers stopped and project-specific images removed."

## purge: DANGEROUS! Delete all containers, images and data volumes
purge:
	@echo "WARNING: This will delete ALL containers, images, and PERSISTENT DATA volumes."
	@read -p "Are you absolutely sure? [y/N] " ans; \
	if [ "$${ans:-N}" = "y" ] || [ "$${ans:-N}" = "Y" ]; then \
	   docker compose down --rmi all --volumes; \
	   echo "System purged. Database volumes have been deleted."; \
	fi

## psql: Open psql session in map database
psql:
	@echo "Ensuring worldmap database is running"
	@docker compose up $(DB_SERVICE) -d
	@docker compose exec $(DB_SERVICE) psql -U $(DB_USER) $(DB_NAME)

## status: Database Status Report
status:
	@echo "--- Ships Located in Each Region ---"
	@docker compose exec -T $(DB_SERVICE) psql -U $(DB_USER) $(DB_NAME) -c \
	"SELECT r.label as region, count(s.mmsi) as ships \
	 FROM map_region r \
	 LEFT JOIN ships s ON ST_Within(s.geom, r.boundary) \
	 GROUP BY r.label \
	 ORDER BY ships DESC;"
	@echo "\n--- Database Composition (Unique Ships) ---"
	@docker compose exec -T $(DB_SERVICE) psql -U $(DB_USER) $(DB_NAME) -c \
	"SELECT \
	    count(*) FILTER (WHERE name != 'Unknown' AND vessel_type != 0) as full_records, \
	    count(*) FILTER (WHERE name = 'Unknown' AND vessel_type = 0) as shadow_records, \
	    count(*) as total \
	 FROM ships;"
	@echo "--- Lightning Strikes in Each Region ---"
	@docker compose exec -T $(DB_SERVICE) psql -U $(DB_USER) $(DB_NAME) -c \
	"SELECT r.label as region, count(l.id) as strikes \
	 FROM map_region r \
	 LEFT JOIN lightning_strikes l ON ST_Within(l.geom, r.boundary) \
	 GROUP BY r.label \
	 ORDER BY strikes DESC;"

## help: Show this help menu
help:
	@echo "Available commands:"
	@sed -n 's/^##//p' $(MAKEFILE_LIST) | awk '{printf "  \033[36m%-20s\033[0m %s\n", $$1, substr($$0, index($$0,$$2))}'
