"""initial schema

Revision ID: 98327e175b52
Revises: 
Create Date: 2026-07-05 09:09:44.108974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98327e175b52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_requests',
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=2), nullable=False),
    sa.Column('fhour', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_date', 'run_id', 'fhour', 'product')
    )
    op.create_index('idx_backfill_status', 'backfill_requests', ['status'], unique=False)
    op.create_table('earthquakes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('mag', sa.REAL(), nullable=True),
    sa.Column('depth', sa.REAL(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('eq_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quakes_geom', 'earthquakes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_quakes_time', 'earthquakes', ['eq_time'], unique=False)
    op.create_table('field_catalog',
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=2), nullable=False),
    sa.Column('fhour', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('nlat', sa.Integer(), nullable=True),
    sa.Column('nlon', sa.Integer(), nullable=True),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('storage_uri', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('run_date', 'run_id', 'fhour', 'product')
    )
    op.create_index('idx_field_catalog_product', 'field_catalog', ['product'], unique=False)
    op.create_index('idx_field_catalog_updated', 'field_catalog', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('lightning_strikes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('lon', sa.REAL(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lightning_geom', 'lightning_strikes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_lightning_time', 'lightning_strikes', ['acquired_at'], unique=False)
    op.create_table('map_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index('idx_ship_regions_boundary', 'map_region', ['boundary'], unique=False, postgresql_using='gist')
    op.create_table('markers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('pop', sa.BigInteger(), nullable=True),
    sa.Column('capital', sa.Boolean(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('wx_temp_c', sa.REAL(), nullable=True),
    sa.Column('wx_humidity_pct', sa.REAL(), nullable=True),
    sa.Column('wx_wind_ms', sa.REAL(), nullable=True),
    sa.Column('wx_wind_dir_deg', sa.REAL(), nullable=True),
    sa.Column('wx_valid_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wx_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_markers_kind_priority', 'markers', ['kind', 'priority'], unique=False)
    op.create_table('process_status',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('satellites',
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('omm', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('norad_id')
    )
    op.create_index('idx_satellites_name', 'satellites', ['name'], unique=False)
    op.create_table('ships',
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vessel_type', sa.Integer(), nullable=True),
    sa.Column('imo', sa.Integer(), nullable=True),
    sa.Column('callsign', sa.String(length=50), nullable=True),
    sa.Column('draught', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prev_draught', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('beam', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.Integer(), nullable=True),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('last_position_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('vessel_class', sa.String(length=50), nullable=True),
    sa.Column('ais_tier', sa.Enum('A', 'B', name='ais_vessel_tier'), nullable=False),
    sa.PrimaryKeyConstraint('mmsi')
    )
    op.create_index('idx_ships_geom', 'ships', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_ships_last_update', 'ships', ['last_position_update'], unique=False)
    op.create_table('storms',
    sa.Column('sid', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cone_geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('volcanoes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('vei', sa.Integer(), nullable=True),
    sa.Column('significant', sa.Boolean(), nullable=True),
    sa.Column('erupt_date_code', sa.String(length=10), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volcano_filters', 'volcanoes', ['vei', 'significant', 'erupt_date_code'], unique=False)
    op.create_index('idx_volcano_geom', 'volcanoes', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('ship_position',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('nav_status', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mmsi'], ['ships.mmsi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ship_pos_geom', 'ship_position', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_ship_pos_mmsi', 'ship_position', ['mmsi'], unique=False)
    op.create_index('idx_ship_pos_time', 'ship_position', ['acquired_at'], unique=False)
    op.create_table('storm_track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(length=10), nullable=True),
    sa.Column('record_type', sa.String(length=10), nullable=True),
    sa.Column('dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tau', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lon', sa.Numeric(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['storms.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storm_track_sid', 'storm_track', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_storm_track_sid', table_name='storm_track')
    op.drop_table('storm_track')
    op.drop_index('idx_ship_pos_time', table_name='ship_position')
    op.drop_index('idx_ship_pos_mmsi', table_name='ship_position')
    op.drop_index('idx_ship_pos_geom', table_name='ship_position', postgresql_using='gist')
    op.drop_table('ship_position')
    op.drop_index('idx_volcano_geom', table_name='volcanoes', postgresql_using='gist')
    op.drop_index('idx_volcano_filters', table_name='volcanoes')
    op.drop_table('volcanoes')
    op.drop_table('storms')
    op.drop_index('idx_ships_last_update', table_name='ships')
    op.drop_index('idx_ships_geom', table_name='ships', postgresql_using='gist')
    op.drop_table('ships')
    op.drop_index('idx_satellites_name', table_name='satellites')
    op.drop_table('satellites')
    op.drop_table('process_status')
    op.drop_index('idx_markers_kind_priority', table_name='markers')
    op.drop_table('markers')
    op.drop_index('idx_ship_regions_boundary', table_name='map_region', postgresql_using='gist')
    op.drop_table('map_region')
    op.drop_index('idx_lightning_time', table_name='lightning_strikes')
    op.drop_index('idx_lightning_geom', table_name='lightning_strikes', postgresql_using='gist')
    op.drop_table('lightning_strikes')
    op.drop_index('idx_field_catalog_updated', table_name='field_catalog')
    op.drop_index('idx_field_catalog_product', table_name='field_catalog')
    op.drop_table('field_catalog')
    op.drop_index('idx_quakes_time', table_name='earthquakes')
    op.drop_index('idx_quakes_geom', table_name='earthquakes', postgresql_using='gist')
    op.drop_table('earthquakes')
    op.drop_index('idx_backfill_status', table_name='backfill_requests')
    op.drop_table('backfill_requests')
    # ### end Alembic commands ###
