[common]
workdir = .

[isobars]
url = https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod
outfile = data/global_isobars.png
isobar_color = White
label_fontsize = 10

[storm_markers]
url = https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/
outfile = data/storm_markers.txt
marker_color=yellow
regional_only=false
expiry_days=3

[quake_markers]
url = https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv
outfile = data/quake_markers.txt
marker_color = White
min_mag = 5.0

[volcano_markers]
url = https://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/volcanoes
outfile = data/volcano_markers.txt
marker_color = DeepPink

[shipping_markers]
url = wss://stream.aisstream.io/v0/stream
api_key = 821e87303ea976ca69fbc18acd955e40d6a6d11c
outfile = data/ship_markers.txt
# Time to listen for positional data broadcasts
listen_for_positional_data = 120
# Time to listen for static data broadcasts
listen_for_static_data = 30
# [Lat South, Lon West, Lat North, Lon East]
# Bounding Box List:
# 1. NZ/Australia (Tasman Sea focused)
# 2. Strait of Hormuz (Entrance to Persian Gulf)
# 3. Suez Canal (North & South entrances)
# 4. Strait of Gibraltar (Entrance to Mediterranean)
# 5. English Channel (Dover Strait focused)
bbox = [[[-48.0, 140.0], [-10.0, 180.0]], [[22.0, 52.0], [28.0, 62.0]], [[27.0, 30.0], [33.0, 35.0]],[[34.0, -9.0], [37.0, -4.0]], [[48.0, -6.0], [52.0, 3.0]]]
harvest_bbox = [[[-90.0, -180.0], [90.0, 180.0]]]
marker_color = orange
show_ship_names = False
# Possible values: ["Tanker", "Cargo"]
show_ship_types = ["Tanker", "Cargo"]

[shipping_harvester]
url = wss://stream.aisstream.io/v0/stream
api_key = 821e87303ea976ca69fbc18acd955e40d6a6d11c
static_database = data/ship_cache.json
# Time to listen for static data broadcasts
listen_for_static_data = 300
harvest_bbox = [[[-90.0, -180.0], [90.0, 180.0]]]
harvest_chunks = 8
