#!/usr/bin/env python3
"""Builds the Country Statistics layer's bundled country polygons from Natural Earth's
1:50m admin-0 countries, plus the backend's matching set of country codes.

Writes:
  ui/geo/countries_50m.json          -- {code, name} per country, coordinates rounded
                                        to 0.01deg (~1 km, about 1:50m's own precision)
  src/atmos_gl/lib/country_codes.py  -- COUNTRY_CODES, the codes those polygons carry

A country's code is ISO_A3_EH, falling back to ADM0_A3 where Natural Earth has no
ISO code (-99): Kosovo (KOS), Somaliland (SOL), Northern Cyprus (CYN), Siachen (KAS).
Natural Earth's default (de facto) point of view on disputed borders is used as-is.

Run from the repo root whenever Natural Earth publishes a release worth picking up:
    uv run python tools/build_country_geometry.py
"""
import json
import urllib.request
from pathlib import Path

SOURCE = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
          "geojson/ne_50m_admin_0_countries.geojson")
ROOT = Path(__file__).resolve().parent.parent
GEOMETRY_OUT = ROOT / "ui" / "geo" / "countries_50m.json"
CODES_OUT = ROOT / "src" / "atmos_gl" / "lib" / "country_codes.py"
DECIMALS = 2


def country_code(properties: dict) -> str:
    code = properties["ISO_A3_EH"]
    return properties["ADM0_A3"] if code == "-99" else code


def _ring(ring: list) -> list:
    """Rounds a ring's points, dropping consecutive duplicates the rounding creates."""
    out = []
    for lon, lat in ring:
        point = [round(lon, DECIMALS), round(lat, DECIMALS)]
        if not out or out[-1] != point:
            out.append(point)
    return out


def _geometry(geometry: dict) -> dict:
    polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
    rounded = [[r for r in map(_ring, polygon) if len(r) >= 4] for polygon in polygons]
    rounded = [p for p in rounded if p]
    if len(rounded) == 1:
        return {"type": "Polygon", "coordinates": rounded[0]}
    return {"type": "MultiPolygon", "coordinates": rounded}


def main() -> None:
    with urllib.request.urlopen(SOURCE, timeout=60) as r:
        source = json.load(r)
    features = [
        {"type": "Feature",
         "properties": {"code": country_code(f["properties"]), "name": f["properties"]["NAME"]},
         "geometry": _geometry(f["geometry"])}
        for f in source["features"]
    ]
    GEOMETRY_OUT.parent.mkdir(parents=True, exist_ok=True)
    GEOMETRY_OUT.write_text(json.dumps(
        {"type": "FeatureCollection", "features": features}, separators=(",", ":")))

    codes = sorted({f["properties"]["code"] for f in features})
    lines = [f'    "{code}",' for code in codes]
    CODES_OUT.write_text(
        '#!/usr/bin/env python3\n'
        '"""Generated by tools/build_country_geometry.py -- do not edit by hand. The\n'
        'country codes the Country Statistics layer\'s bundled polygons\n'
        '(ui/geo/countries_50m.json) carry: values for any other code have nowhere to be\n'
        'drawn."""\n\n'
        'COUNTRY_CODES = frozenset({\n' + "\n".join(lines) + '\n})\n'
    )
    print(f"{len(features)} countries, {len(codes)} codes -> {GEOMETRY_OUT}, {CODES_OUT}")


if __name__ == "__main__":
    main()
